[build]
  command = "mkdir -p ./dist/"
  publish = "./public/"
  

[functions]
  external_node_modules = [
    "ejs",
    "express",
    "@netlify/functions"
  ]
  included_files = [
    "./views/**/*"
  ]
  node_bundler = "esbuild"
[[redirects]]
  from = "/*"
  status = 200
  to = "/.netlify/functions/server/:splat"