[build]
  command = "npm install"
  publish = "public"  
[functions]
  external_node_modules = [
    "ejs",
    "express"
  ]
  included_files = [
    "./views/**/*"
  ]
  node_bundler = "esbuild"
[[redirects]]
  from = "/*"
  status = 200
  to = "/.netlify/functions/server/:splat"