[build]
  command = "mkdir -p ./dist/"
  publish = "./dist/"
[functions]
  external_node_modules = [
    "ejs",
    "express"
  ]
  included_files = [
    "./views/**/*"
    "./public/**/*"
  ]
  node_bundler = "esbuild"
[[redirects]]
  from = "/*"
  status = 200
  to = "/.netlify/functions/server/:splat"