[build]
  command = "npm run build"  # Adjust the build command if you need it
  publish = "public"

[functions]
  directory = "functions"  # Directory where Netlify functions are stored
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
